#!/bin/bash

source ~/.dotfiles/utils

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh


# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

# Symlink the Mackup config
ln -s $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh

echo ""
echo "# ---------------------------------- #"
echo "# Install homebrew                   #"
echo "# ---------------------------------- #"
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/freek/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"


echo 'Install pkg-config'
echo '----------------'
brew_install pkg-config

echo 'Install wget'
echo '----------------'
brew_install wget

echo 'Install hub'
echo '----------------'
brew_install hub

echo 'Install git-secret'
echo '----------------'
brew_install git-secret

brew_install php@8.2

brew_install php@8.1

echo 'Install composer'
echo '-------------'
if [ -e "/usr/local/bin/composer" ]; then
    echo "composer installed"
else
    EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
    if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
    then
        >&2 echo 'ERROR: Invalid installer checksum'
        rm composer-setup.php
        exit 1
    fi
    php composer-setup.php
    rm composer-setup.php
    sudo mkdir /usr/local/bin/
    sudo mv composer.phar /usr/local/bin/composer
fi

brew_install "imagick"

echo 'Install xdebug'
echo '--------------'
pecl install xdebug

echo 'Install redis'
echo '-------------'
pecl install redis

echo 'Install laravel valet'
echo '--------------'
composer global require laravel/valet
valet install
valet trust

brew tap nicoverbruggen/homebrew-cask

brew_install "mackup"

brew_install "zsh-autosuggestions"

echo '++++++++++++++++++++++++++++++'
echo 'Install some nice quicklook plugins'
echo '++++++++++++++++++++++++++++++'
brew_install_cask qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv

echo '++++++++++++++++++++++++++++++'
echo 'Install dev apps'
echo '++++++++++++++++++++++++++++++'
brew_install_cask phpmon dbngin mongodb-compass postman visual-studio-code iterm2 tinkerwell termius figma

echo '++++++++++++++++++++++++++++++'
echo 'Install utils apps'
echo '++++++++++++++++++++++++++++++'
brew_install_cask 1password numi raycast grammarly-desktop grammarly hiddenbar

echo '++++++++++++++++++++++++++++++'
echo 'Install communication apps'
brew_install_cask zoom telegram lark

echo '++++++++++++++++++++++++++++++'
echo 'Install network apps'
echo '++++++++++++++++++++++++++++++'
brew_install_cask outline outline-manager proxyman cyberduck

echo '++++++++++++++++++++++++++++++'
echo 'Install other apps'
echo '++++++++++++++++++++++++++++++'
brew_install_cask betterzip vlc notion netnewswire

echo ""
echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo ""

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo ""
echo '1. Make sure dropbox is running first. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your dropbox. If you already had a backup via mackup run `mackup restore` You'\''ll find more info on Mackup here: https://github.com/lra/mackup.'
echo '2. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '3. Make a .dotfiles-custom/shell/.aliases for your personal commands'
